### PR TITLE
3761 status page

### PR DESCRIPTION
**Pull request by konistehrad**
Close https://github.com/TypeNetwork/typenetwork.com/issues/3761 by creating a status page that fetches from multiple sources and makes composite statuses of those sources. The specifications for the composite statuses can be found here: https://github.com/TypeNetwork/typenetwork.com/issues/3761#issuecomment-329256682. Minor service disruptions are not currently reported to the page, but are reported internally if we decide we care. Example:

All clear:
screen shot 2017-09-14 at 2 33 43 pm

First-party error (celery):
screen shot 2017-09-14 at 2 32 26 pm

Third-party error (EdgeCast):
screen shot 2017-09-14 at 2 36 16 pm

### CODE REVIEW

**Comment by dopry** [comment]
We probably want a degraded notice for services with issues.  As an admin responsible for the support of TN. I'd rather see the everything we depend on in one dashboard. Maybe group external services separately. Sure we can't address it, but we should be aware of it at a glance.

**Comment by konistehrad** [comment]
screen shot 2017-09-19 at 6 32 49 am

@dopry this has been updated to itemize status. The individual statuses are links to the relevant dashboards; in the case of TN services that's NewRelic.

**Comment by paleydreier** [comment]
@konistehrad minor tweak... can we use the TN logo in place of the big TypeNetwork?

**Comment by konistehrad** [comment]
@paleydreier Is this closer to your expectation? I pulled the SVG we use in the corner and changed the fill color from white:

screen shot 2017-09-20 at 8 59 41 am

**Comment by paleydreier** [comment]
@konistehrad not sure what size master the SVG in the corner is, but let's use this one for big sizes.
[TypeNetwork-LogoType_MSD-70_72pt.svg.zip](https://github.com/TypeNetwork/status.typenetwork.com/files/1317807/TypeNetwork-LogoType_MSD-70_72pt.svg.zip)

**Comment by konistehrad** [comment]
@paleydreier updated SVG and "Status" font weight:

screen shot 2017-09-20 at 9 11 24 am

**Comment by paleydreier** [comment]
👍

**Comment by konistehrad** [comment]
@paleydreier excellent, thanks Paley!

**Pull request merged**
